# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        secret: YWUxYzIwNzExYTA4MDk4MTA0MGM4MjU0M2YxNTI0OWMxZGYwMjI0YWNkZDRjZjBlNTEyYmI5OTlhYWY5MjljY2I2OTQ4Nzg3MWYzYWVlYjlmZjE2MGYzZGJkNGUzMGJlMDg1MzJlNDllMTM3MDI0MjMyYzczYjE2OGIwZmI3ZmI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
